name: ragflow

services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION:-8.11.3}
    container_name: ragflow-es-01
    ports:
      - "${ES_PORT:-1200}:9200"
    environment:
      node.name: ragflow-es-01
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-infini_rag_flow}
      bootstrap.memory_lock: "false"
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      cluster.routing.allocation.disk.watermark.low: 5gb
      cluster.routing.allocation.disk.watermark.high: 3gb
      cluster.routing.allocation.disk.watermark.flood_stage: 2gb
      TZ: ${TIMEZONE:-Asia/Shanghai}
    mem_limit: ${MEM_LIMIT:-8073741824}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: on-failure

volumes:
  esdata01:
    external: true
    name: docker_esdata01
