apiVersion: v1
kind: Service
metadata:
  name: openviking-nodeport
  namespace: infra
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: openviking
    app.kubernetes.io/instance: openviking
  ports:
    - name: http
      port: 1933
      targetPort: 1933
      nodePort: 31933
